# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgre
spec:
 replicas: 1
 selector:
  matchLabels:
   app: postgre
 template:
  metadata:
   labels:
    app: postgre
  spec:
   containers:
    - name: postgre
      image: postgre:15.13
      ports:
       - containerPort: 5432
      env:
       - name: POSTGRES_USER
         value: 'review'
       - name: POSTGRES_PASSWORD
         value: 'Passw0rd2023!'
       - name: POSTGRES_DB
         value: 'review'
---
# Service
apiVersion: v1
kind: Service
metadata:
 name: postgre
spec:
 selector:
  app: postgre
 type: ClusterIP
 ports:
  - port: 5432
    targetPort: 5432
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: review
spec:
 replicas: 1
 selector:
  matchLabels:
   app: review
 template:
  metadata:
   labels:
    app: review
  spec:
   containers:
    - name: web
      image: owftecnologia/review-filmes
      ports:
       - containerPort: 8080
      env:
       - name: ASPNETCORE_HTTP_PORTS
         value: '8080'
       - name: ConnectionStrings__DefaultConnection
         value: 'Host=postgre;Database=review;Username=review;Password=Passw0rd2023!'
---
# Service
apiVersion: v1
kind: Service
metadata:
 name: review
spec:
 selector:
  app: review
 type: LoadBalancer
 ports:
  - port: 80
    targetPort: 8080
