name: ci-cd
on:
 push:
  branches: ['main']
 workflow_dispatch:
jobs:
 ci:
  runs-on: ubuntu-latest
  steps:
   - name: Obter o código do projeto
     uses: actions/checkout@v4
   - name: Setup do .NET Core
     uses: actions/setup-dotnet@v3.4.2
     with:
      dotnet-version: 8.x
   - name: Execução de teste
     working-directory: ./review-filmes/src/Review-Filmes.Test.Unit
     run: dotnet test
   - name: Login no Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
   - name: Build e push da aplicação
     uses: docker/build-push-action@v6
     with:
      # Nome da imagem
      tags: |
       owftecnologia/review-filmes:v${{ github.run_number }}
       owftecnologia/review-filmes:latest
      # Contexto
      context: ./review-filmes/src
      # Dockerfile
      file: ./review-filmes/src/Review-Filmes.Web/Dockerfile
      push: true
 cd:
  needs: [ci]
  runs-on: ubuntu-latest
  steps:
   - run: echo "Obter código"
   - run: echo "Configura o Kubeconfig"
   - run: echo "Executar o aply"
